# 🌐 Site Settings
title: Prince Praveen
tagline: A Seasoned DevOps/SRE/Platform Engineer
description: A blog about development, ideas, and learning

# 🌍 URL (IMPORTANT for SEO + domain)
url: "https://blog.princepraveen.co.in"

# 🕒 Timezone
timezone: Asia/Kolkata

# 👤 Author
author:
  name: Prince Praveen

# 🎨 Theme (Chirpy uses this)
theme: jekyll-theme-chirpy
theme_mode: dark

# 🔗 Social (optional but useful)
github:
  username: princechennai

# 📄 Pagination (default works fine)
paginate: 10

exclude:
  - "*.gem"
  - "*.gemspec"
  - docs
  - tools
  - README.md
  - LICENSE
  - purgecss.js
  - "*.config.js"
  - "package*.json"

avatar: /assets/img/avatar.jpg   # add your photo here
social:
  name: Prince Praveen
  links:
    - https://github.com/princechennai
    - https://linkedin.com/in/princecrown