# 🌐 Site Settings
title: Prince Praveen
tagline: A Seasoned DevOps/SRE/Platform Engineer
description: A blog about development, ideas, and learning

# 🌍 URL (IMPORTANT for SEO + domain)
url: "https://blog.princepraveen.co.in"

# 🕒 Timezone
timezone: Asia/Kolkata

# 👤 Author
author:
  name: Prince Praveen

# 🎨 Theme (Chirpy uses this)
theme: minima

# 🔗 Social (optional but useful)
github:
  username: princechennai

# 📄 Pagination (default works fine)
paginate: 10
markdown: kramdown